### ISSUE TITLE
Error: Cannot find module 'fs-promise'

### ISSUE THREAD

**Issue by TxHawks** [jonathantneal/mdcss#39]
My gulpfile has a `import mdcss from 'mdcss';` line in it, and throws the following error stack whenever Gulp is run:

```sh
Error: Cannot find module 'fs-promise'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/txh/test/node_modules/mdcss/index.js:2:11)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/txh/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/txh/test/gulpfile.babel.js:16:1)
    at Module._compile (module.js:556:32)
    at loader (/home/txh/test/node_modules/babel-register/lib/node.js:144:5)
```

If the above line is commented out, the error goes away.

**Comment by stephenway** [comment]
I'm in the process of trying to unpublish 1.5.3 because it has some breaking changes. For now roll back to 1.5.2 and it should fix your problem in the interim.
https://github.com/npm/npm/issues/15061

**Comment by TxHawks** [comment]
Thanks

**Comment by iGitScor** [comment]
Hello @stephenway,

why did you not publish version 1.5.4 ?

Thanks

**Comment by stephenway** [comment]
Time crunched at the moment. Anyone want to do this? Someone needs to fix testing as the latest isn't stable. I'm not comfortable publishing anything until that gets resolved.

**Comment by jarodtaylor** [comment]
I'm assuming this hasn't been resolved? We have to roll back to version 1.5.2?

**Comment by iGitScor** [comment]
Not resolved yet @jarodtaylor. I did the same (rollback to 1.5.2) 😞

**Comment by stephenway** [comment]
Sorry guys, I just removed 1.5.3 so next time you install it won't give you something broken.
